# Data handling
library(dplyr)
library(tidyr)
library(readr)
library(purrr)
library(stringr)
library(lubridate)
library(terra)
library(sf)
library(foreign)
library(units)
library(whitebox)

# Analysis
library(mlr3verse)
library(mlr3spatiotempcv)
library(ranger)
library(mgcv)
library(future)
library(furrr)
library(deming)
library(rstudioapi)
library(tictoc)

# Visualisation
library(ggplot2)
library(tmap)
library(grid)
library(patchwork)
library(ggthemes)
library(ggpmisc)
library(gratia)
